version: "3.8"

services:
  client:
    container_name: task-organizer-client
    restart: always
    build:
      context: ../../app/client
      dockerfile: Dockerfile.dev
    env_file:
      - ../env/dev/client.env
    volumes:
      - ../../app/client/src:/app/src
      - /app/node_modules
    depends_on:
      - server
    ports:
      - 5173:5173
    networks:
      - task-organizer

  server:
    container_name: task-organizer-server
    restart: always
    build:
      context: ../../app/server
      dockerfile: Dockerfile.dev
    env_file:
      - ../env/dev/server.env
    volumes:
      - ../../app/server/src:/app/src
      - /app/node_modules
    depends_on:
      - database
    ports:
      - 1306:1306
    networks:
      - task-organizer

  database:
    container_name: task-organizer-database
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ../../database/data:/var/lib/postgresql/data/
    networks:
      - task-organizer

  pgadmin:
    container_name: task-organizer-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ../../database/pgadmin:/var/lib/pgadmin
    ports:
      - 88:80
    networks:
      - task-organizer

networks:
  task-organizer:
    name: task-organizer
    driver: bridge
